extern const GeoLayout bowser_2_area_1_geo[];
extern const GeoLayout bowser_2_area_1[];
extern const Collision bowser_2_area_1_collision[];
extern const MacroObject bowser_2_area_1_macro_objs[];
#include "src/game/camera.h"

extern struct CutsceneSplinePoint bowser_2_area_1_spline_mh_cam[];
extern struct CutsceneSplinePoint bowser_2_area_1_spline_mh_cam2[];
extern struct CutsceneSplinePoint bowser_2_area_1_spline_mh_cam3[];
extern struct CutsceneSplinePoint bowser_2_area_1_spline_mh_foc[];
extern struct CutsceneSplinePoint bowser_2_area_1_spline_mh_foc2[];
extern struct CutsceneSplinePoint bowser_2_area_1_spline_mh_foc3[];
extern const GeoLayout bowser_2_area_2_geo[];
extern const GeoLayout bowser_2_area_2[];
extern const Collision bowser_2_area_2_collision[];
extern const MacroObject bowser_2_area_2_macro_objs[];
extern u8 bowser_2_dl__11111texKinokoRed_ci4_ci4[];
extern u8 bowser_2_dl__11111texKinokoRed_ci4_pal_rgba16[];
extern u8 bowser_2_dl_door_birch_lower_ci4_ci4[];
extern u8 bowser_2_dl_door_birch_lower_ci4_pal_rgba16[];
extern u8 bowser_2_dl__1chain_ci4_ci4[];
extern u8 bowser_2_dl__1chain_ci4_pal_rgba16[];
extern u8 bowser_2_dl_PNIDSNE_ci4_ci4[];
extern u8 bowser_2_dl_PNIDSNE_ci4_pal_rgba16[];
extern u8 bowser_2_dl_DK_grass_ci4_ci4[];
extern u8 bowser_2_dl_DK_grass_ci4_pal_rgba16[];
extern u8 bowser_2_dl_stone_granite_rgba16_ci8[];
extern u8 bowser_2_dl_stone_granite_rgba16_pal_rgba16[];
extern u8 bowser_2_dl__1_rgba16_i8[];
extern u8 bowser_2_dl_water_ci4[];
extern u8 bowser_2_dl_water_pal_rgba16[];
extern u8 bowser_2_dl_brick_ci8[];
extern u8 bowser_2_dl_brick_pal_rgba16[];
extern u8 bowser_2_dl_NSwitch_GameWatch_Legendary_Sideimg_Bush_rgba16[];
extern u8 bowser_2_dl_mushroom_ci4[];
extern u8 bowser_2_dl_mushroom_pal_rgba16[];
extern Vtx bowser_2_dl_Circle_004_mesh_layer_1_vtx_cull[8];
extern Vtx bowser_2_dl_Circle_004_mesh_layer_1_vtx_0[467];
extern Gfx bowser_2_dl_Circle_004_mesh_layer_1_tri_0[];
extern Vtx bowser_2_dl_Circle_004_mesh_layer_1_vtx_1[386];
extern Gfx bowser_2_dl_Circle_004_mesh_layer_1_tri_1[];
extern Vtx bowser_2_dl_Circle_004_mesh_layer_5_vtx_cull[8];
extern Vtx bowser_2_dl_Circle_004_mesh_layer_5_vtx_0[13];
extern Gfx bowser_2_dl_Circle_004_mesh_layer_5_tri_0[];
extern Vtx bowser_2_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx bowser_2_dl_Cube_001_mesh_layer_1_vtx_0[170];
extern Gfx bowser_2_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bowser_2_dl_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx bowser_2_dl_Mesh_mesh_layer_1_vtx_0[274];
extern Gfx bowser_2_dl_Mesh_mesh_layer_1_tri_0[];
extern Vtx bowser_2_dl_Mesh_mesh_layer_1_vtx_1[597];
extern Gfx bowser_2_dl_Mesh_mesh_layer_1_tri_1[];
extern Vtx bowser_2_dl_MovableBox_mesh_layer_1_vtx_cull[8];
extern Vtx bowser_2_dl_MovableBox_mesh_layer_1_vtx_0[48];
extern Gfx bowser_2_dl_MovableBox_mesh_layer_1_tri_0[];
extern Vtx bowser_2_dl_Water_Box_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx bowser_2_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx bowser_2_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Vtx bowser_2_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bowser_2_dl_Cube_mesh_layer_1_vtx_0[352];
extern Gfx bowser_2_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bowser_2_dl_Cube_mesh_layer_1_vtx_1[168];
extern Gfx bowser_2_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bowser_2_dl_Cube_mesh_layer_4_vtx_cull[8];
extern Vtx bowser_2_dl_Cube_mesh_layer_4_vtx_0[28];
extern Gfx bowser_2_dl_Cube_mesh_layer_4_tri_0[];
extern Vtx bowser_2_dl_DeathPlane_mesh_layer_5_vtx_cull[8];
extern Vtx bowser_2_dl_DeathPlane_mesh_layer_5_vtx_0[4];
extern Gfx bowser_2_dl_DeathPlane_mesh_layer_5_tri_0[];
extern Gfx mat_bowser_2_dl_f3dlite_material_026[];
extern Gfx mat_revert_bowser_2_dl_f3dlite_material_026[];
extern Gfx mat_bowser_2_dl_f3dlite_material_027[];
extern Gfx mat_revert_bowser_2_dl_f3dlite_material_027[];
extern Gfx mat_bowser_2_dl_f3dlite_material_028[];
extern Gfx mat_revert_bowser_2_dl_f3dlite_material_028[];
extern Gfx mat_bowser_2_dl_f3dlite_material_006[];
extern Gfx mat_revert_bowser_2_dl_f3dlite_material_006[];
extern Gfx mat_bowser_2_dl_material_1_001_f3d[];
extern Gfx mat_revert_bowser_2_dl_material_1_001_f3d[];
extern Gfx mat_bowser_2_dl_material_2_001_f3d[];
extern Gfx mat_revert_bowser_2_dl_material_2_001_f3d[];
extern Gfx mat_bowser_2_dl_f3dlite_material_003[];
extern Gfx mat_revert_bowser_2_dl_f3dlite_material_003[];
extern Gfx mat_bowser_2_dl_sm64_water_mat[];
extern Gfx mat_revert_bowser_2_dl_sm64_water_mat[];
extern Gfx mat_bowser_2_dl_f3dlite_material_008[];
extern Gfx mat_revert_bowser_2_dl_f3dlite_material_008[];
extern Gfx mat_bowser_2_dl_f3dlite_material_009[];
extern Gfx mat_revert_bowser_2_dl_f3dlite_material_009[];
extern Gfx mat_bowser_2_dl_f3dlite_material_010[];
extern Gfx mat_revert_bowser_2_dl_f3dlite_material_010[];
extern Gfx mat_bowser_2_dl_f3dlite_material_011[];
extern Gfx mat_revert_bowser_2_dl_f3dlite_material_011[];
extern Gfx bowser_2_dl_Circle_004_mesh_layer_1[];
extern Gfx bowser_2_dl_Circle_004_mesh_layer_5[];
extern Gfx bowser_2_dl_Cube_001_mesh_layer_1[];
extern Gfx bowser_2_dl_Mesh_mesh_layer_1[];
extern Gfx bowser_2_dl_MovableBox_mesh_layer_1[];
extern Gfx bowser_2_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx bowser_2_dl_final_revert_mesh_layer_1[];
extern Gfx bowser_2_dl_final_revert_mesh_layer_5[];
extern Gfx bowser_2_dl_Cube_mesh_layer_1[];
extern Gfx bowser_2_dl_Cube_mesh_layer_4[];
extern Gfx bowser_2_dl_DeathPlane_mesh_layer_5[];
extern Gfx bowser_2_dl_final_revert_mesh_layer_1_001[];
extern Gfx bowser_2_dl_final_revert_mesh_layer_4[];
extern Gfx bowser_2_dl_final_revert_mesh_layer_5_001[];
