extern const GeoLayout mgMoveBox_geo[];
extern u8 mgMoveBox__6__2__ci4_ci4[];
extern u8 mgMoveBox__6__2__ci4_pal_rgba16[];
extern Vtx mgMoveBox_MovableBox_mesh_layer_1_vtx_cull[8];
extern Vtx mgMoveBox_MovableBox_mesh_layer_1_vtx_0[48];
extern Gfx mgMoveBox_MovableBox_mesh_layer_1_tri_0[];
extern Gfx mat_mgMoveBox_f3dlite_material_003[];
extern Gfx mat_revert_mgMoveBox_f3dlite_material_003[];
extern Gfx mgMoveBox_MovableBox_mesh_layer_1[];
extern Gfx mgMoveBox_final_revert_mesh_layer_1[];
