extern const GeoLayout mgMoveBox_geo[];
extern u8 mgMoveBox_rr_textures_01000_rgba16_ci8[];
extern u8 mgMoveBox_rr_textures_01000_rgba16_pal_rgba16[];
extern Vtx mgMoveBox_MovableBox_mesh_layer_1_vtx_cull[8];
extern Vtx mgMoveBox_MovableBox_mesh_layer_1_vtx_0[44];
extern Gfx mgMoveBox_MovableBox_mesh_layer_1_tri_0[];
extern Gfx mat_mgMoveBox_f3dlite_material_003[];
extern Gfx mat_revert_mgMoveBox_f3dlite_material_003[];
extern Gfx mgMoveBox_MovableBox_mesh_layer_1[];
extern Gfx mgMoveBox_final_revert_mesh_layer_1[];
