#include "src/game/envfx_snow.h"

const GeoLayout mario_armature_002_switch_option_009[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, Geo_Switch_DoNothing),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_1),
			GEO_BRANCH(1, mario_geo_opt_2_1),
			GEO_BRANCH(1, mario_geo_opt_3_1),
			GEO_BRANCH(1, mario_geo_opt_4_1),
			GEO_BRANCH(1, mario_geo_opt_5_1),
			GEO_BRANCH(1, mario_geo_opt_6_1),
			GEO_BRANCH(1, mario_geo_opt_7_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_Capoff1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, Geo_Switch_DoNothing),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_2),
			GEO_BRANCH(1, mario_geo_opt_2_2),
			GEO_BRANCH(1, mario_geo_opt_3_2),
			GEO_BRANCH(1, mario_geo_opt_4_2),
			GEO_BRANCH(1, mario_geo_opt_5_2),
			GEO_BRANCH(1, mario_geo_opt_6_2),
			GEO_BRANCH(1, mario_geo_opt_7_2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_CapOff2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, Geo_Switch_DoNothing),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_3),
			GEO_BRANCH(1, mario_geo_opt_2_3),
			GEO_BRANCH(1, mario_geo_opt_3_3),
			GEO_BRANCH(1, mario_geo_opt_4_3),
			GEO_BRANCH(1, mario_geo_opt_5_3),
			GEO_BRANCH(1, mario_geo_opt_6_3),
			GEO_BRANCH(1, mario_geo_opt_7_3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_002_switch_option_right_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_002_switch_option_left_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_004_switch_option_left_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_005_switch_option_left_hand_cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_006_switch_option_left_hand_wing_cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4_with_layer_4_revert),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_1),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_1),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_4_opt_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_1_opt_1),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_1_opt_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_1_opt_1),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_4_opt_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_1_opt_2),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_1_opt_2),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_1_opt_2),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_4_opt_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_1_opt_2),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_1_opt_2),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_1_opt_2),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_4_opt_1_opt_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_1_opt_2),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_1_opt_2),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_1_opt_2),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_4_opt_1_opt_5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_1_opt_2),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_1_opt_2),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_1_opt_2),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_4_opt_1_opt_6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_1_opt_2),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_1_opt_2),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_1_opt_2),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_4_opt_1_opt_7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_1_opt_2),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_1_opt_2),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_1_opt_2),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_armature_002_switch_option_009_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, Geo_Switch_DoNothing),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_1_0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_1_opt_1),
			GEO_BRANCH(1, mario_geo_opt_2_1_opt_1),
			GEO_BRANCH(1, mario_geo_opt_3_1_opt_1),
			GEO_BRANCH(1, mario_geo_opt_4_1_opt_1),
			GEO_BRANCH(1, mario_geo_opt_5_1_opt_1),
			GEO_BRANCH(1, mario_geo_opt_6_1_opt_1),
			GEO_BRANCH(1, mario_geo_opt_7_1_opt_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_1_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_Capoff1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, Geo_Switch_DoNothing),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_1_0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_2_opt_1),
			GEO_BRANCH(1, mario_geo_opt_2_2_opt_1),
			GEO_BRANCH(1, mario_geo_opt_3_2_opt_1),
			GEO_BRANCH(1, mario_geo_opt_4_2_opt_1),
			GEO_BRANCH(1, mario_geo_opt_5_2_opt_1),
			GEO_BRANCH(1, mario_geo_opt_6_2_opt_1),
			GEO_BRANCH(1, mario_geo_opt_7_2_opt_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_2_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_1_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_2_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_2_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_2_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_2_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_2_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_2_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_1_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_CapOff2_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, Geo_Switch_DoNothing),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_1_0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_3_opt_1),
			GEO_BRANCH(1, mario_geo_opt_2_3_opt_1),
			GEO_BRANCH(1, mario_geo_opt_3_3_opt_1),
			GEO_BRANCH(1, mario_geo_opt_4_3_opt_1),
			GEO_BRANCH(1, mario_geo_opt_5_3_opt_1),
			GEO_BRANCH(1, mario_geo_opt_6_3_opt_1),
			GEO_BRANCH(1, mario_geo_opt_7_3_opt_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_3_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_1_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_3_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_3_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_3_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_3_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_3_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_1_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_3_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_1_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_open_armature_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_002_switch_option_right_hand_open_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_open_armature_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_002_switch_option_left_hand_open_mesh_layer_1_opt_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_peace_armature_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_004_switch_option_left_hand_peace_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_cap_armature_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_005_switch_option_left_hand_cap_mesh_layer_1_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_wing_cap_armature_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_opt_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_mesh_layer_1_opt_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_001_skinned_mesh_layer_1_opt_1),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_000_offset_001_mesh_layer_1_opt_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_001_mesh_layer_4_opt_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_1_0),
												GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_1_0),
												GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_1_0),
												GEO_ASM(0, Geo_MarioNoseJiggle),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, mario_geo_opt_1_4_opt_1_opt_1),
											GEO_BRANCH(1, mario_geo_opt_1_4_opt_1_opt_2),
											GEO_BRANCH(1, mario_geo_opt_1_4_opt_1_opt_3),
											GEO_BRANCH(1, mario_geo_opt_1_4_opt_1_opt_4),
											GEO_BRANCH(1, mario_geo_opt_1_4_opt_1_opt_5),
											GEO_BRANCH(1, mario_geo_opt_1_4_opt_1_opt_6),
											GEO_BRANCH(1, mario_geo_opt_1_4_opt_1_opt_7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, mario_armature_002_switch_option_009_opt_1),
									GEO_BRANCH(1, mario_Capoff1_opt_1),
									GEO_BRANCH(1, mario_CapOff2_opt_1),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_001_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_002_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_003_skinned_mesh_layer_1_opt_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_003_mesh_layer_1_opt_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_004_skinned_mesh_layer_1_opt_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_000_offset_004_mesh_layer_1_opt_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_TRANSPARENT, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_003_mesh_layer_1_opt_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, mario_right_hand_open_armature_opt_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_006_skinned_mesh_layer_1_opt_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_006_mesh_layer_1_opt_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_007_skinned_mesh_layer_1_opt_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_000_offset_007_mesh_layer_1_opt_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_TRANSPARENT, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_004_mesh_layer_1_opt_1),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, mario_left_hand_open_armature_opt_1),
										GEO_BRANCH(1, mario_left_hand_peace_armature_opt_1),
										GEO_BRANCH(1, mario_left_hand_cap_armature_opt_1),
										GEO_BRANCH(1, mario_left_hand_wing_cap_armature_opt_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_009_skinned_mesh_layer_1_opt_1),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_009_mesh_layer_1_opt_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_010_skinned_mesh_layer_1_opt_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_000_offset_010_mesh_layer_1_opt_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_011_skinned_mesh_layer_1_opt_1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_000_offset_011_mesh_layer_1_opt_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_012_skinned_mesh_layer_1_opt_1),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_012_mesh_layer_1_opt_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_013_skinned_mesh_layer_1_opt_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_000_offset_013_mesh_layer_1_opt_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_005_skinned_mesh_layer_1_opt_1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_TRANSPARENT, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_005_mesh_layer_1_opt_1_with_layer_5_revert),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_4_opt_2_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_4_opt_2_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_4_opt_2_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_4_opt_2_opt_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_4_opt_2_opt_5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_4_opt_2_opt_6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_4_opt_2_opt_7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_armature_002_switch_option_009_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, Geo_Switch_DoNothing),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_1_opt_2),
			GEO_BRANCH(1, mario_geo_opt_2_1_opt_2),
			GEO_BRANCH(1, mario_geo_opt_3_1_opt_2),
			GEO_BRANCH(1, mario_geo_opt_4_1_opt_2),
			GEO_BRANCH(1, mario_geo_opt_5_1_opt_2),
			GEO_BRANCH(1, mario_geo_opt_6_1_opt_2),
			GEO_BRANCH(1, mario_geo_opt_7_1_opt_2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_Capoff1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, Geo_Switch_DoNothing),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_2_opt_2),
			GEO_BRANCH(1, mario_geo_opt_2_2_opt_2),
			GEO_BRANCH(1, mario_geo_opt_3_2_opt_2),
			GEO_BRANCH(1, mario_geo_opt_4_2_opt_2),
			GEO_BRANCH(1, mario_geo_opt_5_2_opt_2),
			GEO_BRANCH(1, mario_geo_opt_6_2_opt_2),
			GEO_BRANCH(1, mario_geo_opt_7_2_opt_2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_2_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_2_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_2_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_2_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_2_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_2_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_2_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_CapOff2_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, Geo_Switch_DoNothing),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_3_opt_2),
			GEO_BRANCH(1, mario_geo_opt_2_3_opt_2),
			GEO_BRANCH(1, mario_geo_opt_3_3_opt_2),
			GEO_BRANCH(1, mario_geo_opt_4_3_opt_2),
			GEO_BRANCH(1, mario_geo_opt_5_3_opt_2),
			GEO_BRANCH(1, mario_geo_opt_6_3_opt_2),
			GEO_BRANCH(1, mario_geo_opt_7_3_opt_2),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_3_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_3_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_3_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_3_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_3_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_3_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_3_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_open_armature_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_002_switch_option_right_hand_open_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_open_armature_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_002_switch_option_left_hand_open_mesh_layer_1_opt_2),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_peace_armature_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_004_switch_option_left_hand_peace_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_cap_armature_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_005_switch_option_left_hand_cap_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_wing_cap_armature_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_opt_2),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4_with_layer_4_revert),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_mesh_layer_1_opt_2),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_001_skinned_mesh_layer_1_opt_2),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_000_offset_001_mesh_layer_1_opt_2),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, mario_000_offset_001_mesh_layer_4_opt_2),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1_opt_2_0),
												GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
												GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
												GEO_ASM(0, Geo_MarioNoseJiggle),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, mario_geo_opt_2_4_opt_2_opt_1),
											GEO_BRANCH(1, mario_geo_opt_2_4_opt_2_opt_2),
											GEO_BRANCH(1, mario_geo_opt_2_4_opt_2_opt_3),
											GEO_BRANCH(1, mario_geo_opt_2_4_opt_2_opt_4),
											GEO_BRANCH(1, mario_geo_opt_2_4_opt_2_opt_5),
											GEO_BRANCH(1, mario_geo_opt_2_4_opt_2_opt_6),
											GEO_BRANCH(1, mario_geo_opt_2_4_opt_2_opt_7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, mario_armature_002_switch_option_009_opt_2),
									GEO_BRANCH(1, mario_Capoff1_opt_2),
									GEO_BRANCH(1, mario_CapOff2_opt_2),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mario_000_displaylist_001_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mario_000_displaylist_002_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_003_skinned_mesh_layer_1_opt_2),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_003_mesh_layer_1_opt_2),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_004_skinned_mesh_layer_1_opt_2),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_000_offset_004_mesh_layer_1_opt_2),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_003_mesh_layer_1_opt_2),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, mario_right_hand_open_armature_opt_2),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_006_skinned_mesh_layer_1_opt_2),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_006_mesh_layer_1_opt_2),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_007_skinned_mesh_layer_1_opt_2),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_000_offset_007_mesh_layer_1_opt_2),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_004_mesh_layer_1_opt_2),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, mario_left_hand_open_armature_opt_2),
										GEO_BRANCH(1, mario_left_hand_peace_armature_opt_2),
										GEO_BRANCH(1, mario_left_hand_cap_armature_opt_2),
										GEO_BRANCH(1, mario_left_hand_wing_cap_armature_opt_2),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_009_skinned_mesh_layer_1_opt_2),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_009_mesh_layer_1_opt_2),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_010_skinned_mesh_layer_1_opt_2),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_000_offset_010_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_011_skinned_mesh_layer_1_opt_2),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_000_offset_011_mesh_layer_1_opt_2),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_012_skinned_mesh_layer_1_opt_2),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_012_mesh_layer_1_opt_2),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_013_skinned_mesh_layer_1_opt_2),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_000_offset_013_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_005_skinned_mesh_layer_1_opt_2),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_005_mesh_layer_1_opt_2_with_layer_1_revert),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_4_opt_3_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_4_opt_3_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_4_opt_3_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_4_opt_3_opt_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_4_opt_3_opt_5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_4_opt_3_opt_6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_4_opt_3_opt_7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
		GEO_ASM(0, Geo_MarioNoseJiggle),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_armature_002_switch_option_009_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, Geo_Switch_DoNothing),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_1_opt_3),
			GEO_BRANCH(1, mario_geo_opt_2_1_opt_3),
			GEO_BRANCH(1, mario_geo_opt_3_1_opt_3),
			GEO_BRANCH(1, mario_geo_opt_4_1_opt_3),
			GEO_BRANCH(1, mario_geo_opt_5_1_opt_3),
			GEO_BRANCH(1, mario_geo_opt_6_1_opt_3),
			GEO_BRANCH(1, mario_geo_opt_7_1_opt_3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_346346457z_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_Capoff1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, Geo_Switch_DoNothing),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_2_opt_3),
			GEO_BRANCH(1, mario_geo_opt_2_2_opt_3),
			GEO_BRANCH(1, mario_geo_opt_3_2_opt_3),
			GEO_BRANCH(1, mario_geo_opt_4_2_opt_3),
			GEO_BRANCH(1, mario_geo_opt_5_2_opt_3),
			GEO_BRANCH(1, mario_geo_opt_6_2_opt_3),
			GEO_BRANCH(1, mario_geo_opt_7_2_opt_3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_2_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_2_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_2_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_2_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_2_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_2_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_2_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap_32465346_mesh_layer_1_opt_2_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_CapOff2_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, Geo_Switch_DoNothing),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_geo_opt_1_3_opt_3),
			GEO_BRANCH(1, mario_geo_opt_2_3_opt_3),
			GEO_BRANCH(1, mario_geo_opt_3_3_opt_3),
			GEO_BRANCH(1, mario_geo_opt_4_3_opt_3),
			GEO_BRANCH(1, mario_geo_opt_5_3_opt_3),
			GEO_BRANCH(1, mario_geo_opt_6_3_opt_3),
			GEO_BRANCH(1, mario_geo_opt_7_3_opt_3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_1_3_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_2_3_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_3_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_4_3_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_5_3_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_6_3_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_7_3_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_right_hand_open_armature_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_002_switch_option_right_hand_open_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_open_armature_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_002_switch_option_left_hand_open_mesh_layer_1_opt_2),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_peace_armature_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_004_switch_option_left_hand_peace_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_cap_armature_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_005_switch_option_left_hand_cap_mesh_layer_1_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_left_hand_wing_cap_armature_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_opt_2),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo_opt_3_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_mesh_layer_1_opt_2),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_001_skinned_mesh_layer_1_opt_2),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_000_offset_001_mesh_layer_1_opt_2),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_001_mesh_layer_4_opt_2),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_mesh_layer_1_opt_2_0),
												GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_NoseTranslateRotate_skinned_mesh_layer_1_opt_2_0),
												GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_TRANSPARENT, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1_opt_2_0),
												GEO_ASM(0, Geo_MarioNoseJiggle),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, mario_geo_opt_3_4_opt_3_opt_1),
											GEO_BRANCH(1, mario_geo_opt_3_4_opt_3_opt_2),
											GEO_BRANCH(1, mario_geo_opt_3_4_opt_3_opt_3),
											GEO_BRANCH(1, mario_geo_opt_3_4_opt_3_opt_4),
											GEO_BRANCH(1, mario_geo_opt_3_4_opt_3_opt_5),
											GEO_BRANCH(1, mario_geo_opt_3_4_opt_3_opt_6),
											GEO_BRANCH(1, mario_geo_opt_3_4_opt_3_opt_7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, mario_armature_002_switch_option_009_opt_3),
									GEO_BRANCH(1, mario_Capoff1_opt_3),
									GEO_BRANCH(1, mario_CapOff2_opt_3),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_001_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_002_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_003_skinned_mesh_layer_1_opt_2),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_003_mesh_layer_1_opt_2),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_004_skinned_mesh_layer_1_opt_2),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_000_offset_004_mesh_layer_1_opt_2),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_TRANSPARENT, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_003_mesh_layer_1_opt_2),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, mario_right_hand_open_armature_opt_3),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_006_skinned_mesh_layer_1_opt_2),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_006_mesh_layer_1_opt_2),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_007_skinned_mesh_layer_1_opt_2),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, mario_000_offset_007_mesh_layer_1_opt_2),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_TRANSPARENT, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_004_mesh_layer_1_opt_2),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, mario_left_hand_open_armature_opt_3),
										GEO_BRANCH(1, mario_left_hand_peace_armature_opt_3),
										GEO_BRANCH(1, mario_left_hand_cap_armature_opt_3),
										GEO_BRANCH(1, mario_left_hand_wing_cap_armature_opt_3),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_009_skinned_mesh_layer_1_opt_2),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_009_mesh_layer_1_opt_2),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_010_skinned_mesh_layer_1_opt_2),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_000_offset_010_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_011_skinned_mesh_layer_1_opt_2),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_000_offset_011_mesh_layer_1_opt_2),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_012_skinned_mesh_layer_1_opt_2),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_012_mesh_layer_1_opt_2),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_013_skinned_mesh_layer_1_opt_2),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_000_offset_013_mesh_layer_1_opt_2),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_005_skinned_mesh_layer_1_opt_2),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_TRANSPARENT, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_005_mesh_layer_1_opt_2_with_layer_1_revert),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_ASM(1, geo_mario_lights),
			GEO_ASM(0, geo_mirror_mario_backface_culling),
			GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_001_skinned_mesh_layer_1),
							GEO_ASM(0, geo_mario_tilt_torso),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_000_offset_001_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_ALPHA, mario_000_offset_001_mesh_layer_4),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_head_rotation),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_mesh_layer_1),
															GEO_ASM(0, Geo_ApplyMarioNoseJiggle),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_NoseTranslateRotate_skinned_mesh_layer_1),
															GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 83, 103, 0, 0, 0, 0, mario_NoseTranslateRotate_mesh_layer_1),
															GEO_ASM(0, Geo_MarioNoseJiggle),
														GEO_CLOSE_NODE(),
														GEO_BRANCH(1, mario_geo_opt_1),
														GEO_BRANCH(1, mario_geo_opt_2),
														GEO_BRANCH(1, mario_geo_opt_3),
														GEO_BRANCH(1, mario_geo_opt_4),
														GEO_BRANCH(1, mario_geo_opt_5),
														GEO_BRANCH(1, mario_geo_opt_6),
														GEO_BRANCH(1, mario_geo_opt_7),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_armature_002_switch_option_009),
												GEO_BRANCH(1, mario_Capoff1),
												GEO_BRANCH(1, mario_CapOff2),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
												GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_ALPHA, mario_000_displaylist_001_mesh_layer_4),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
												GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_ALPHA, mario_000_displaylist_002_mesh_layer_4),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_003_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_003_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_004_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_000_offset_004_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(1, geo_switch_mario_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_003_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, mario_right_hand_open_armature),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_006_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_006_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_007_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_000_offset_007_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_004_mesh_layer_1),
															GEO_CLOSE_NODE(),
															GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, mario_left_hand_open_armature),
													GEO_BRANCH(1, mario_left_hand_peace_armature),
													GEO_BRANCH(1, mario_left_hand_cap_armature),
													GEO_BRANCH(1, mario_left_hand_wing_cap_armature),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_009_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_009_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_010_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_000_offset_010_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_011_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_000_offset_011_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_012_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_012_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_013_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_000_offset_013_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_005_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(2, geo_mario_hand_foot_scaler),
											GEO_SCALE(LAYER_FORCE, 65536),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_005_mesh_layer_1_with_layer_1_revert),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, mario_geo_opt_1_4),
				GEO_BRANCH(1, mario_geo_opt_2_4),
				GEO_BRANCH(1, mario_geo_opt_3_4),
			GEO_CLOSE_NODE(),
			GEO_ASM(1, geo_mario_reset_lights),
			GEO_ASM(1, geo_mirror_mario_backface_culling),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
