extern const GeoLayout mario_armature_002_switch_option_002[];
extern const GeoLayout mario_right_hand_open_armature[];
extern const GeoLayout mario_left_hand_open_armature[];
extern const GeoLayout mario_left_hand_peace_armature[];
extern const GeoLayout mario_left_hand_cap_armature[];
extern const GeoLayout mario_left_hand_wing_cap_armature[];
extern const GeoLayout mario_geo_opt_1[];
extern const GeoLayout mario_geo_opt_2[];
extern const GeoLayout mario_geo_opt_3[];
extern const GeoLayout mario_geo_opt_4[];
extern const GeoLayout mario_geo_opt_5[];
extern const GeoLayout mario_geo_opt_6[];
extern const GeoLayout mario_geo_opt_7[];
extern const GeoLayout mario_geo_opt_1_1[];
extern const GeoLayout mario_geo_opt_2_1[];
extern const GeoLayout mario_geo_opt_3_1[];
extern const GeoLayout mario_geo_opt_4_1[];
extern const GeoLayout mario_geo_opt_5_1[];
extern const GeoLayout mario_geo_opt_6_1[];
extern const GeoLayout mario_geo_opt_7_1[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_1[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_2[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_3[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_4[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_5[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_6[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_7[];
extern const GeoLayout mario_armature_002_switch_option_002_opt_1[];
extern const GeoLayout mario_geo_opt_1_1_opt_1[];
extern const GeoLayout mario_geo_opt_2_1_opt_1[];
extern const GeoLayout mario_geo_opt_3_1_opt_1[];
extern const GeoLayout mario_geo_opt_4_1_opt_1[];
extern const GeoLayout mario_geo_opt_5_1_opt_1[];
extern const GeoLayout mario_geo_opt_6_1_opt_1[];
extern const GeoLayout mario_geo_opt_7_1_opt_1[];
extern const GeoLayout mario_right_hand_open_armature_opt_1[];
extern const GeoLayout mario_left_hand_open_armature_opt_1[];
extern const GeoLayout mario_left_hand_peace_armature_opt_1[];
extern const GeoLayout mario_left_hand_cap_armature_opt_1[];
extern const GeoLayout mario_left_hand_wing_cap_armature_opt_1[];
extern const GeoLayout mario_geo_opt_1_2[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_1[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_2[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_3[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_4[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_5[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_6[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_7[];
extern const GeoLayout mario_armature_002_switch_option_002_opt_2[];
extern const GeoLayout mario_geo_opt_1_1_opt_2[];
extern const GeoLayout mario_geo_opt_2_1_opt_2[];
extern const GeoLayout mario_geo_opt_3_1_opt_2[];
extern const GeoLayout mario_geo_opt_4_1_opt_2[];
extern const GeoLayout mario_geo_opt_5_1_opt_2[];
extern const GeoLayout mario_geo_opt_6_1_opt_2[];
extern const GeoLayout mario_geo_opt_7_1_opt_2[];
extern const GeoLayout mario_right_hand_open_armature_opt_2[];
extern const GeoLayout mario_left_hand_open_armature_opt_2[];
extern const GeoLayout mario_left_hand_peace_armature_opt_2[];
extern const GeoLayout mario_left_hand_cap_armature_opt_2[];
extern const GeoLayout mario_left_hand_wing_cap_armature_opt_2[];
extern const GeoLayout mario_geo_opt_2_2[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_1[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_2[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_3[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_4[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_5[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_6[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_7[];
extern const GeoLayout mario_armature_002_switch_option_002_opt_3[];
extern const GeoLayout mario_geo_opt_1_1_opt_3[];
extern const GeoLayout mario_geo_opt_2_1_opt_3[];
extern const GeoLayout mario_geo_opt_3_1_opt_3[];
extern const GeoLayout mario_geo_opt_4_1_opt_3[];
extern const GeoLayout mario_geo_opt_5_1_opt_3[];
extern const GeoLayout mario_geo_opt_6_1_opt_3[];
extern const GeoLayout mario_geo_opt_7_1_opt_3[];
extern const GeoLayout mario_right_hand_open_armature_opt_3[];
extern const GeoLayout mario_left_hand_open_armature_opt_3[];
extern const GeoLayout mario_left_hand_peace_armature_opt_3[];
extern const GeoLayout mario_left_hand_cap_armature_opt_3[];
extern const GeoLayout mario_left_hand_wing_cap_armature_opt_3[];
extern const GeoLayout mario_geo_opt_3_2[];
extern const GeoLayout mario_geo[];
extern Lights1 mario_blue_v4_lights;
extern Lights1 mario_body_v4_lights;
extern Lights1 mario_red_v4_lights;
extern Lights1 mario_cap_v4_001_lights;
extern Lights1 mario_face_0___eye_open_v4_001_lights;
extern Lights1 mario_hair_v4_001_lights;
extern Lights1 mario_skin_001_lights;
extern Lights1 mario_mustache_lights;
extern Lights1 mario_cap_v4_lights;
extern Lights1 mario_sideburns_v4_001_lights;
extern Lights1 mario_mustache_v4_001_lights;
extern Lights1 mario_gloves_v4_001_lights;
extern Lights1 mario_shoes_v4_001_lights;
extern Lights1 mario_face_1___eye_half_v4_001_lights;
extern Lights1 mario_face_2___eye_closed_v4_001_lights;
extern Lights1 mario_face_7___eye_X_v4_001_lights;
extern Lights1 mario_metal_v4_001_lights;
extern u8 mario_mario_overallsbutton_ci8[];
extern u8 mario_mario_overallsbutton_pal_rgba16[];
extern u8 mario_eye_rgba16[];
extern u8 mario_mario_logo_rgba16_ci4[];
extern u8 mario_mario_logo_rgba16_pal_rgba16[];
extern u8 mario_mario_sideburn_raymarch_aa_v1_idk_4_ia8[];
extern u8 mario_mustach_ult_raymarch_aa_v0_ci4[];
extern u8 mario_mustach_ult_raymarch_aa_v0_pal_rgba16[];
extern u8 mario_mario_wing_rgba16_ia8[];
extern u8 mario_Unbenannt_1_ci4[];
extern u8 mario_Unbenannt_1_pal_rgba16[];
extern u8 mario_mario_shoe__copy__ci4[];
extern u8 mario_mario_shoe__copy__pal_rgba16[];
extern u8 mario_raymarch_eye_attempt5_halfclose_coop_recolor_ci8[];
extern u8 mario_raymarch_eye_attempt5_halfclose_coop_recolor_pal_rgba16[];
extern u8 mario_raymarch_eye_attempt5_close_coop_recolor_ci4[];
extern u8 mario_raymarch_eye_attempt5_close_coop_recolor_pal_rgba16[];
extern u8 mario_mario_eye3_ci4[];
extern u8 mario_mario_eye3_pal_rgba16[];
extern u8 mario_fortn_ice_mario_2_ci8[];
extern u8 mario_fortn_ice_mario_2_pal_rgba16[];
extern Vtx mario_000_offset_mesh_layer_1_vtx_0[18];
extern Gfx mario_000_offset_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_001_skinned_mesh_layer_1_vtx_0[11];
extern Gfx mario_000_offset_001_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_001_mesh_layer_1_vtx_0[11];
extern Gfx mario_000_offset_001_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_001_mesh_layer_1_vtx_1[12];
extern Gfx mario_000_offset_001_mesh_layer_1_tri_1[];
extern Vtx mario_000_offset_001_mesh_layer_1_vtx_2[42];
extern Gfx mario_000_offset_001_mesh_layer_1_tri_2[];
extern Vtx mario_000_offset_001_mesh_layer_1_vtx_3[19];
extern Gfx mario_000_offset_001_mesh_layer_1_tri_3[];
extern Vtx mario_000_displaylist_mesh_layer_1_vtx_0[53];
extern Gfx mario_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx mario_000_displaylist_mesh_layer_1_vtx_1[109];
extern Gfx mario_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx mario_000_displaylist_mesh_layer_1_vtx_2[17];
extern Gfx mario_000_displaylist_mesh_layer_1_tri_2[];
extern Vtx mario_000_displaylist_mesh_layer_1_vtx_3[12];
extern Gfx mario_000_displaylist_mesh_layer_1_tri_3[];
extern Vtx mario_000_displaylist_mesh_layer_1_vtx_4[23];
extern Gfx mario_000_displaylist_mesh_layer_1_tri_4[];
extern Vtx mario_000_displaylist_mesh_layer_5_vtx_0[14];
extern Gfx mario_000_displaylist_mesh_layer_5_tri_0[];
extern Vtx mario_000_displaylist_mesh_layer_5_vtx_1[12];
extern Gfx mario_000_displaylist_mesh_layer_5_tri_1[];
extern Vtx mario_002_switch_option_head__no_cap__mesh_layer_1_vtx_0[87];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_head__no_cap__mesh_layer_1_vtx_1[18];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_head__no_cap__mesh_layer_1_vtx_2[12];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_tri_2[];
extern Vtx mario_002_switch_option_head__no_cap__mesh_layer_1_vtx_3[86];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_tri_3[];
extern Vtx mario_002_switch_option_head__no_cap__mesh_layer_5_vtx_0[12];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_5_tri_0[];
extern Vtx mario_000_displaylist_001_mesh_layer_4_vtx_0[6];
extern Gfx mario_000_displaylist_001_mesh_layer_4_tri_0[];
extern Vtx mario_000_displaylist_002_mesh_layer_4_vtx_0[6];
extern Gfx mario_000_displaylist_002_mesh_layer_4_tri_0[];
extern Vtx mario_000_offset_003_skinned_mesh_layer_1_vtx_0[6];
extern Gfx mario_000_offset_003_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_003_mesh_layer_1_vtx_0[6];
extern Gfx mario_000_offset_003_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_003_mesh_layer_1_vtx_1[10];
extern Gfx mario_000_offset_003_mesh_layer_1_tri_1[];
extern Vtx mario_000_offset_004_skinned_mesh_layer_1_vtx_0[7];
extern Gfx mario_000_offset_004_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_004_mesh_layer_1_vtx_0[6];
extern Gfx mario_000_offset_004_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_004_mesh_layer_1_vtx_1[8];
extern Gfx mario_000_offset_004_mesh_layer_1_tri_1[];
extern Vtx mario_000_displaylist_003_mesh_layer_1_vtx_0[41];
extern Gfx mario_000_displaylist_003_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_right_hand_open_mesh_layer_1_vtx_0[42];
extern Gfx mario_002_switch_option_right_hand_open_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_006_skinned_mesh_layer_1_vtx_0[6];
extern Gfx mario_000_offset_006_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_006_mesh_layer_1_vtx_0[6];
extern Gfx mario_000_offset_006_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_006_mesh_layer_1_vtx_1[11];
extern Gfx mario_000_offset_006_mesh_layer_1_tri_1[];
extern Vtx mario_000_offset_007_skinned_mesh_layer_1_vtx_0[6];
extern Gfx mario_000_offset_007_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_007_mesh_layer_1_vtx_0[6];
extern Gfx mario_000_offset_007_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_007_mesh_layer_1_vtx_1[8];
extern Gfx mario_000_offset_007_mesh_layer_1_tri_1[];
extern Vtx mario_000_displaylist_004_mesh_layer_1_vtx_0[36];
extern Gfx mario_000_displaylist_004_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_left_hand_open_mesh_layer_1_vtx_0[42];
extern Gfx mario_002_switch_option_left_hand_open_mesh_layer_1_tri_0[];
extern Vtx mario_004_switch_option_left_hand_peace_mesh_layer_1_vtx_0[61];
extern Gfx mario_004_switch_option_left_hand_peace_mesh_layer_1_tri_0[];
extern Vtx mario_005_switch_option_left_hand_cap_mesh_layer_1_vtx_0[31];
extern Gfx mario_005_switch_option_left_hand_cap_mesh_layer_1_tri_0[];
extern Vtx mario_005_switch_option_left_hand_cap_mesh_layer_1_vtx_1[43];
extern Gfx mario_005_switch_option_left_hand_cap_mesh_layer_1_tri_1[];
extern Vtx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_vtx_0[31];
extern Gfx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_tri_0[];
extern Vtx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_vtx_1[43];
extern Gfx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_tri_1[];
extern Vtx mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4_vtx_0[12];
extern Gfx mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4_tri_0[];
extern Vtx mario_000_offset_009_skinned_mesh_layer_1_vtx_0[8];
extern Gfx mario_000_offset_009_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_009_mesh_layer_1_vtx_0[5];
extern Gfx mario_000_offset_009_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_010_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_000_offset_010_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_010_mesh_layer_1_vtx_0[5];
extern Gfx mario_000_offset_010_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_011_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_000_offset_011_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_011_mesh_layer_1_vtx_0[6];
extern Gfx mario_000_offset_011_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_011_mesh_layer_1_vtx_1[23];
extern Gfx mario_000_offset_011_mesh_layer_1_tri_1[];
extern Vtx mario_000_offset_012_skinned_mesh_layer_1_vtx_0[8];
extern Gfx mario_000_offset_012_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_012_mesh_layer_1_vtx_0[5];
extern Gfx mario_000_offset_012_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_013_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_000_offset_013_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_013_mesh_layer_1_vtx_0[5];
extern Gfx mario_000_offset_013_mesh_layer_1_tri_0[];
extern Vtx mario_000_displaylist_005_skinned_mesh_layer_1_vtx_0[5];
extern Gfx mario_000_displaylist_005_skinned_mesh_layer_1_tri_0[];
extern Vtx mario_000_displaylist_005_mesh_layer_1_vtx_0[6];
extern Gfx mario_000_displaylist_005_mesh_layer_1_tri_0[];
extern Vtx mario_000_displaylist_005_mesh_layer_1_vtx_1[23];
extern Gfx mario_000_displaylist_005_mesh_layer_1_tri_1[];
extern Gfx mat_mario_blue_v4[];
extern Gfx mat_revert_mario_blue_v4[];
extern Gfx mat_mario_body_v4[];
extern Gfx mat_revert_mario_body_v4[];
extern Gfx mat_mario_red_v4[];
extern Gfx mat_revert_mario_red_v4[];
extern Gfx mat_mario_cap_v4_001[];
extern Gfx mat_revert_mario_cap_v4_001[];
extern Gfx mat_mario_face_0___eye_open_v4_001[];
extern Gfx mat_revert_mario_face_0___eye_open_v4_001[];
extern Gfx mat_mario_hair_v4_001[];
extern Gfx mat_revert_mario_hair_v4_001[];
extern Gfx mat_mario_skin_001[];
extern Gfx mat_revert_mario_skin_001[];
extern Gfx mat_mario_mustache[];
extern Gfx mat_revert_mario_mustache[];
extern Gfx mat_mario_cap_v4[];
extern Gfx mat_revert_mario_cap_v4[];
extern Gfx mat_mario_sideburns_v4_001[];
extern Gfx mat_revert_mario_sideburns_v4_001[];
extern Gfx mat_mario_mustache_v4_001[];
extern Gfx mat_revert_mario_mustache_v4_001[];
extern Gfx mat_mario_wing_1_v4_001[];
extern Gfx mat_revert_mario_wing_1_v4_001[];
extern Gfx mat_mario_gloves_v4_001[];
extern Gfx mat_revert_mario_gloves_v4_001[];
extern Gfx mat_mario_shoes_v4_001[];
extern Gfx mat_revert_mario_shoes_v4_001[];
extern Gfx mat_mario_face_1___eye_half_v4_001[];
extern Gfx mat_revert_mario_face_1___eye_half_v4_001[];
extern Gfx mat_mario_face_2___eye_closed_v4_001[];
extern Gfx mat_revert_mario_face_2___eye_closed_v4_001[];
extern Gfx mat_mario_face_7___eye_X_v4_001[];
extern Gfx mat_revert_mario_face_7___eye_X_v4_001[];
extern Gfx mat_mario_metal_v4_001[];
extern Gfx mat_revert_mario_metal_v4_001[];
extern Gfx mario_000_offset_mesh_layer_1[];
extern Gfx mario_000_offset_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_001_skinned_mesh_layer_1[];
extern Gfx mario_000_offset_001_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_001_mesh_layer_1[];
extern Gfx mario_000_offset_001_mesh_layer_1_opt_2[];
extern Gfx mario_000_displaylist_mesh_layer_1[];
extern Gfx mario_000_displaylist_mesh_layer_1_opt_1[];
extern Gfx mario_000_displaylist_mesh_layer_1_opt_2[];
extern Gfx mario_000_displaylist_mesh_layer_1_opt_7[];
extern Gfx mario_000_displaylist_mesh_layer_1_opt_2_0[];
extern Gfx mario_000_displaylist_mesh_layer_5[];
extern Gfx mario_000_displaylist_mesh_layer_5_opt_2[];
extern Gfx mario_000_displaylist_mesh_layer_5_with_revert[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_opt_1[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_opt_7[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_0[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_1[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_2[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2_3[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_5[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_5_opt_2[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_5_with_revert[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_5_opt_2_with_revert[];
extern Gfx mario_000_displaylist_001_mesh_layer_4[];
extern Gfx mario_000_displaylist_002_mesh_layer_4[];
extern Gfx mario_000_offset_003_skinned_mesh_layer_1[];
extern Gfx mario_000_offset_003_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_003_mesh_layer_1[];
extern Gfx mario_000_offset_003_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_004_skinned_mesh_layer_1[];
extern Gfx mario_000_offset_004_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_004_mesh_layer_1[];
extern Gfx mario_000_offset_004_mesh_layer_1_opt_2[];
extern Gfx mario_000_displaylist_003_mesh_layer_1[];
extern Gfx mario_000_displaylist_003_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_right_hand_open_mesh_layer_1[];
extern Gfx mario_002_switch_option_right_hand_open_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_006_skinned_mesh_layer_1[];
extern Gfx mario_000_offset_006_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_006_mesh_layer_1[];
extern Gfx mario_000_offset_006_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_007_skinned_mesh_layer_1[];
extern Gfx mario_000_offset_007_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_007_mesh_layer_1[];
extern Gfx mario_000_offset_007_mesh_layer_1_opt_2[];
extern Gfx mario_000_displaylist_004_mesh_layer_1[];
extern Gfx mario_000_displaylist_004_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_left_hand_open_mesh_layer_1[];
extern Gfx mario_002_switch_option_left_hand_open_mesh_layer_1_opt_2[];
extern Gfx mario_004_switch_option_left_hand_peace_mesh_layer_1[];
extern Gfx mario_004_switch_option_left_hand_peace_mesh_layer_1_opt_2[];
extern Gfx mario_005_switch_option_left_hand_cap_mesh_layer_1[];
extern Gfx mario_005_switch_option_left_hand_cap_mesh_layer_1_opt_2[];
extern Gfx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1[];
extern Gfx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_opt_2[];
extern Gfx mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4[];
extern Gfx mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4_with_layer_4_revert[];
extern Gfx mario_000_offset_009_skinned_mesh_layer_1[];
extern Gfx mario_000_offset_009_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_009_mesh_layer_1[];
extern Gfx mario_000_offset_009_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_010_skinned_mesh_layer_1[];
extern Gfx mario_000_offset_010_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_010_mesh_layer_1[];
extern Gfx mario_000_offset_010_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_011_skinned_mesh_layer_1[];
extern Gfx mario_000_offset_011_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_011_mesh_layer_1[];
extern Gfx mario_000_offset_011_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_012_skinned_mesh_layer_1[];
extern Gfx mario_000_offset_012_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_012_mesh_layer_1[];
extern Gfx mario_000_offset_012_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_013_skinned_mesh_layer_1[];
extern Gfx mario_000_offset_013_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_013_mesh_layer_1[];
extern Gfx mario_000_offset_013_mesh_layer_1_opt_2[];
extern Gfx mario_000_displaylist_005_skinned_mesh_layer_1[];
extern Gfx mario_000_displaylist_005_skinned_mesh_layer_1_opt_2[];
extern Gfx mario_000_displaylist_005_mesh_layer_1_with_layer_1_revert[];
extern Gfx mario_000_displaylist_005_mesh_layer_1_opt_2_with_layer_1_revert[];
extern Gfx mario_000_displaylist_005_mesh_layer_1_with_layer_5_revert[];
