extern const GeoLayout rr_area_1_geo[];
extern const GeoLayout rr_area_1[];
extern const Collision rr_area_1_collision[];
extern const MacroObject rr_area_1_macro_objs[];
extern u8 rr_dl_GrassTestie_png_i4[];
extern u8 rr_dl_TexturesCom_Cement_1x1_512_height_png_i4[];
extern u8 rr_dl_stone_granite_ci8_rgba16[];
extern u8 rr_dl_YukkinaTreeBreak00_ci4_ci4[];
extern u8 rr_dl_YukkinaTreeBreak00_ci4_pal_rgba16[];
extern u8 rr_dl_BigTreeWoodC_rgba16_ci8[];
extern u8 rr_dl_BigTreeWoodC_rgba16_pal_rgba16[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_0[100];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_1[101];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_1[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_2[67];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_2[];
extern Vtx rr_dl_Cylinder_mesh_layer_1_vtx_3[11];
extern Gfx rr_dl_Cylinder_mesh_layer_1_tri_3[];
extern Gfx mat_rr_dl_f3dlite_material[];
extern Gfx mat_revert_rr_dl_f3dlite_material[];
extern Gfx mat_rr_dl_f3dlite_material_001[];
extern Gfx mat_revert_rr_dl_f3dlite_material_001[];
extern Gfx mat_rr_dl_f3dlite_material_002[];
extern Gfx mat_revert_rr_dl_f3dlite_material_002[];
extern Gfx mat_rr_dl_f3dlite_material_003[];
extern Gfx mat_revert_rr_dl_f3dlite_material_003[];
extern Gfx rr_dl_Cylinder_mesh_layer_1[];
extern Gfx rr_dl_final_revert_mesh_layer_1[];
