extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
#include "src/game/camera.h"

extern struct CutsceneSplinePoint castle_grounds_area_1_spline_Cutscene[];
extern struct CutsceneSplinePoint castle_grounds_area_1_spline_Focus[];
extern u8 castle_grounds_dl_castle_grounds_textures_00000_rgba16_ci8[];
extern u8 castle_grounds_dl_castle_grounds_textures_00000_rgba16_pal_rgba16[];
extern u8 castle_grounds_dl_GM4E01_690ee59b_14_mip2_ci4_ci4[];
extern u8 castle_grounds_dl_GM4E01_690ee59b_14_mip2_ci4_pal_rgba16[];
extern u8 castle_grounds_dl_side_ci8[];
extern u8 castle_grounds_dl_side_pal_rgba16[];
extern u8 castle_grounds_dl_ttm_textures_07000_rgba16_ci8[];
extern u8 castle_grounds_dl_ttm_textures_07000_rgba16_pal_rgba16[];
extern u8 castle_grounds_dl_wf_textures_00800_rgba16_ci8[];
extern u8 castle_grounds_dl_wf_textures_00800_rgba16_pal_rgba16[];
extern Vtx castle_grounds_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Circle_mesh_layer_1_vtx_0[99];
extern Gfx castle_grounds_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Circle_mesh_layer_1_vtx_1[51];
extern Gfx castle_grounds_dl_Circle_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Circle_mesh_layer_1_vtx_2[37];
extern Gfx castle_grounds_dl_Circle_mesh_layer_1_tri_2[];
extern Vtx castle_grounds_dl_Cone_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cone_mesh_layer_1_vtx_0[16];
extern Gfx castle_grounds_dl_Cone_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cone_mesh_layer_1_vtx_1[150];
extern Gfx castle_grounds_dl_Cone_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Cone_mesh_layer_1_vtx_2[30];
extern Gfx castle_grounds_dl_Cone_mesh_layer_1_tri_2[];
extern Vtx castle_grounds_dl_Cone_001_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cone_001_mesh_layer_1_vtx_0[16];
extern Gfx castle_grounds_dl_Cone_001_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cone_001_mesh_layer_1_vtx_1[120];
extern Gfx castle_grounds_dl_Cone_001_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Cone_001_mesh_layer_1_vtx_2[30];
extern Gfx castle_grounds_dl_Cone_001_mesh_layer_1_tri_2[];
extern Gfx mat_castle_grounds_dl_Grass_Example[];
extern Gfx mat_revert_castle_grounds_dl_Grass_Example[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_005[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_005[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_003[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_003[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_002[];
extern Gfx castle_grounds_dl_Circle_mesh_layer_1[];
extern Gfx castle_grounds_dl_Cone_mesh_layer_1[];
extern Gfx castle_grounds_dl_Cone_001_mesh_layer_1[];
extern Gfx castle_grounds_dl_final_revert_mesh_layer_1[];
