extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
#include "src/game/camera.h"

extern struct CutsceneSplinePoint castle_grounds_area_1_spline_Cutscene[];
extern struct CutsceneSplinePoint castle_grounds_area_1_spline_Focus[];
extern u8 castle_grounds_dl_sand_ci4[];
extern u8 castle_grounds_dl_sand_pal_rgba16[];
extern u8 castle_grounds_dl_wf_textures_00000_rgba16_ci8[];
extern u8 castle_grounds_dl_wf_textures_00000_rgba16_pal_rgba16[];
extern u8 castle_grounds_dl_Grass_ci4[];
extern u8 castle_grounds_dl_Grass_pal_rgba16[];
extern u8 castle_grounds_dl_Dirt_ci4[];
extern u8 castle_grounds_dl_Dirt_pal_rgba16[];
extern u8 castle_grounds_dl_water_ci4[];
extern u8 castle_grounds_dl_water_pal_rgba16[];
extern u8 castle_grounds_dl_brick_ci8[];
extern u8 castle_grounds_dl_brick_pal_rgba16[];
extern Vtx castle_grounds_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Circle_mesh_layer_1_vtx_0[76];
extern Gfx castle_grounds_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_4_vtx_cull[8];
extern Vtx castle_grounds_dl_Cube_mesh_layer_4_vtx_0[72];
extern Gfx castle_grounds_dl_Cube_mesh_layer_4_tri_0[];
extern Vtx castle_grounds_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Cylinder_mesh_layer_1_vtx_0[32];
extern Gfx castle_grounds_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cylinder_mesh_layer_1_vtx_1[142];
extern Gfx castle_grounds_dl_Cylinder_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_Water_Box_Mesh_001_mesh_layer_5_vtx_cull[8];
extern Vtx castle_grounds_dl_Water_Box_Mesh_001_mesh_layer_5_vtx_0[4];
extern Gfx castle_grounds_dl_Water_Box_Mesh_001_mesh_layer_5_tri_0[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_007[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_007[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_004[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_004[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_006[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_006[];
extern Gfx mat_castle_grounds_dl_sm64_water_mat[];
extern Gfx mat_revert_castle_grounds_dl_sm64_water_mat[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_002[];
extern Gfx castle_grounds_dl_Circle_mesh_layer_1[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_4[];
extern Gfx castle_grounds_dl_Cylinder_mesh_layer_1[];
extern Gfx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx castle_grounds_dl_Water_Box_Mesh_001_mesh_layer_5[];
extern Gfx castle_grounds_dl_final_revert_mesh_layer_1[];
extern Gfx castle_grounds_dl_final_revert_mesh_layer_4[];
extern Gfx castle_grounds_dl_final_revert_mesh_layer_5[];
