extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
#include "src/game/camera.h"

extern struct CutsceneSplinePoint bob_area_1_spline_mh_cam[];
extern struct CutsceneSplinePoint bob_area_1_spline_mh_cam2[];
extern struct CutsceneSplinePoint bob_area_1_spline_mh_cam3[];
extern struct CutsceneSplinePoint bob_area_1_spline_mh_cam4[];
extern struct CutsceneSplinePoint bob_area_1_spline_mh_foc[];
extern struct CutsceneSplinePoint bob_area_1_spline_mh_foc2[];
extern struct CutsceneSplinePoint bob_area_1_spline_mh_foc3[];
extern struct CutsceneSplinePoint bob_area_1_spline_mh_foc4[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern u8 bob_dl__11111texKinokoRed_ci4_ci4[];
extern u8 bob_dl__11111texKinokoRed_ci4_pal_rgba16[];
extern u8 bob_dl_door_birch_lower_ci4_ci4[];
extern u8 bob_dl_door_birch_lower_ci4_pal_rgba16[];
extern u8 bob_dl__1chain_ci4_ci4[];
extern u8 bob_dl__1chain_ci4_pal_rgba16[];
extern u8 bob_dl__66_ci4[];
extern u8 bob_dl__66_pal_rgba16[];
extern u8 bob_dl__16_ci8[];
extern u8 bob_dl__16_pal_rgba16[];
extern u8 bob_dl__18_ci8[];
extern u8 bob_dl__18_pal_rgba16[];
extern u8 bob_dl__17_ci8[];
extern u8 bob_dl__17_pal_rgba16[];
extern u8 bob_dl__86_ci8[];
extern u8 bob_dl__86_pal_rgba16[];
extern u8 bob_dl__94_ci8[];
extern u8 bob_dl__94_pal_rgba16[];
extern u8 bob_dl__95_ci8[];
extern u8 bob_dl__95_pal_rgba16[];
extern u8 bob_dl_DK_grass_ci4_1__1__ci4[];
extern u8 bob_dl_DK_grass_ci4_1__1__pal_rgba16[];
extern u8 bob_dl_ci4_sophie_desertstone_ci4[];
extern u8 bob_dl_ci4_sophie_desertstone_pal_rgba16[];
extern u8 bob_dl__2EB6628BD0351A22F3163295E64E9B63_ci4_ci4[];
extern u8 bob_dl__2EB6628BD0351A22F3163295E64E9B63_ci4_pal_rgba16[];
extern u8 bob_dl_Texture0201_RGB_ci8_ci8[];
extern u8 bob_dl_Texture0201_RGB_ci8_pal_rgba16[];
extern u8 bob_dl_frs_step_01_3C680_ci8_ci8[];
extern u8 bob_dl_frs_step_01_3C680_ci8_pal_rgba16[];
extern u8 bob_dl_sun_ia8[];
extern u8 bob_dl_cloud1_ci4_ci4[];
extern u8 bob_dl_cloud1_ci4_pal_rgba16[];
extern u8 bob_dl_leaf_half_rgba16_ci8[];
extern u8 bob_dl_leaf_half_rgba16_pal_rgba16[];
extern u8 bob_dl_cloud_ia8[];
extern u8 bob_dl__6__2__ci4_ci4[];
extern u8 bob_dl__6__2__ci4_pal_rgba16[];
extern u8 bob_dl_water_ci4[];
extern u8 bob_dl_water_pal_rgba16[];
extern u8 bob_dl_YukkinaTreeBreak00_ci4_ci4[];
extern u8 bob_dl_YukkinaTreeBreak00_ci4_pal_rgba16[];
extern u8 bob_dl_Window_2_ci8[];
extern u8 bob_dl_Window_2_pal_rgba16[];
extern u8 bob_dl_brick_ci8[];
extern u8 bob_dl_brick_pal_rgba16[];
extern u8 bob_dl_BigTreeCourse_ci4_ci4[];
extern u8 bob_dl_BigTreeCourse_ci4_pal_rgba16[];
extern Vtx bob_dl_Circle_004_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Circle_004_mesh_layer_1_vtx_0[467];
extern Gfx bob_dl_Circle_004_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Circle_004_mesh_layer_1_vtx_1[396];
extern Gfx bob_dl_Circle_004_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Circle_004_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Circle_004_mesh_layer_5_vtx_0[13];
extern Gfx bob_dl_Circle_004_mesh_layer_5_tri_0[];
extern Vtx bob_dl_greenery__mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_greenery__mesh_layer_1_vtx_0[490];
extern Gfx bob_dl_greenery__mesh_layer_1_tri_0[];
extern Vtx bob_dl_greenery__mesh_layer_1_vtx_1[152];
extern Gfx bob_dl_greenery__mesh_layer_1_tri_1[];
extern Vtx bob_dl_greenery__mesh_layer_4_vtx_cull[8];
extern Vtx bob_dl_greenery__mesh_layer_4_vtx_0[96];
extern Gfx bob_dl_greenery__mesh_layer_4_tri_0[];
extern Vtx bob_dl_greenery__mesh_layer_4_vtx_1[38];
extern Gfx bob_dl_greenery__mesh_layer_4_tri_1[];
extern Vtx bob_dl_greenery__mesh_layer_4_vtx_2[192];
extern Gfx bob_dl_greenery__mesh_layer_4_tri_2[];
extern Vtx bob_dl_greenery__mesh_layer_4_vtx_3[400];
extern Gfx bob_dl_greenery__mesh_layer_4_tri_3[];
extern Vtx bob_dl_greenery__mesh_layer_4_vtx_4[384];
extern Gfx bob_dl_greenery__mesh_layer_4_tri_4[];
extern Vtx bob_dl_house_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_house_mesh_layer_1_vtx_0[68];
extern Gfx bob_dl_house_mesh_layer_1_tri_0[];
extern Vtx bob_dl_house_mesh_layer_1_vtx_1[68];
extern Gfx bob_dl_house_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Mesh_mesh_layer_1_vtx_0[231];
extern Gfx bob_dl_Mesh_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Mesh_mesh_layer_1_vtx_1[520];
extern Gfx bob_dl_Mesh_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Mesh_mesh_layer_1_vtx_2[47];
extern Gfx bob_dl_Mesh_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Mesh_mesh_layer_1_vtx_3[9];
extern Gfx bob_dl_Mesh_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Mesh_mesh_layer_1_vtx_4[72];
extern Gfx bob_dl_Mesh_mesh_layer_1_tri_4[];
extern Vtx bob_dl_Mesh_mesh_layer_1_vtx_5[57];
extern Gfx bob_dl_Mesh_mesh_layer_1_tri_5[];
extern Vtx bob_dl_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Mesh_mesh_layer_5_vtx_0[12];
extern Gfx bob_dl_Mesh_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Mesh_mesh_layer_5_vtx_1[24];
extern Gfx bob_dl_Mesh_mesh_layer_5_tri_1[];
extern Vtx bob_dl_Mesh_mesh_layer_5_vtx_2[36];
extern Gfx bob_dl_Mesh_mesh_layer_5_tri_2[];
extern Vtx bob_dl_MovableBox_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_MovableBox_mesh_layer_1_vtx_0[48];
extern Gfx bob_dl_MovableBox_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Water_Box_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[151];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[144];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_0[12];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Death_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Death_Plane_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Death_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Circle_mesh_layer_1_vtx_0[67];
extern Gfx bob_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Circle_mesh_layer_1_vtx_1[16];
extern Gfx bob_dl_Circle_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Circle_mesh_layer_1_vtx_2[18];
extern Gfx bob_dl_Circle_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[125];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_f3dlite_material_026[];
extern Gfx mat_revert_bob_dl_f3dlite_material_026[];
extern Gfx mat_bob_dl_f3dlite_material_027[];
extern Gfx mat_revert_bob_dl_f3dlite_material_027[];
extern Gfx mat_bob_dl_f3dlite_material_028[];
extern Gfx mat_revert_bob_dl_f3dlite_material_028[];
extern Gfx mat_bob_dl__66_f3d[];
extern Gfx mat_revert_bob_dl__66_f3d[];
extern Gfx mat_bob_dl__16_f3d[];
extern Gfx mat_revert_bob_dl__16_f3d[];
extern Gfx mat_bob_dl__18_f3d[];
extern Gfx mat_revert_bob_dl__18_f3d[];
extern Gfx mat_bob_dl__17_f3d[];
extern Gfx mat_revert_bob_dl__17_f3d[];
extern Gfx mat_bob_dl__86_f3d[];
extern Gfx mat_revert_bob_dl__86_f3d[];
extern Gfx mat_bob_dl__94_f3d[];
extern Gfx mat_revert_bob_dl__94_f3d[];
extern Gfx mat_bob_dl__95_f3d[];
extern Gfx mat_revert_bob_dl__95_f3d[];
extern Gfx mat_bob_dl_material_1_001_f3d[];
extern Gfx mat_revert_bob_dl_material_1_001_f3d[];
extern Gfx mat_bob_dl_material_2_001_f3d[];
extern Gfx mat_revert_bob_dl_material_2_001_f3d[];
extern Gfx mat_bob_dl_f3dlite_material_005[];
extern Gfx mat_revert_bob_dl_f3dlite_material_005[];
extern Gfx mat_bob_dl_f3dlite_material_007[];
extern Gfx mat_revert_bob_dl_f3dlite_material_007[];
extern Gfx mat_bob_dl_f3dlite_material_012[];
extern Gfx mat_revert_bob_dl_f3dlite_material_012[];
extern Gfx mat_bob_dl_f3dlite_material_014[];
extern Gfx mat_revert_bob_dl_f3dlite_material_014[];
extern Gfx mat_bob_dl_f3dlite_material_016[];
extern Gfx mat_revert_bob_dl_f3dlite_material_016[];
extern Gfx mat_bob_dl_f3dlite_material_020[];
extern Gfx mat_revert_bob_dl_f3dlite_material_020[];
extern Gfx mat_bob_dl_f3dlite_material_018[];
extern Gfx mat_revert_bob_dl_f3dlite_material_018[];
extern Gfx mat_bob_dl_f3dlite_material_003[];
extern Gfx mat_revert_bob_dl_f3dlite_material_003[];
extern Gfx mat_bob_dl_sm64_water_mat[];
extern Gfx mat_revert_bob_dl_sm64_water_mat[];
extern Gfx mat_bob_dl_f3dlite_material_004[];
extern Gfx mat_revert_bob_dl_f3dlite_material_004[];
extern Gfx mat_bob_dl_f3dlite_material_023[];
extern Gfx mat_revert_bob_dl_f3dlite_material_023[];
extern Gfx mat_bob_dl_f3dlite_material_011[];
extern Gfx mat_revert_bob_dl_f3dlite_material_011[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_revert_bob_dl_f3dlite_material[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_revert_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_f3dlite_material_002[];
extern Gfx mat_revert_bob_dl_f3dlite_material_002[];
extern Gfx bob_dl_Circle_004_mesh_layer_1[];
extern Gfx bob_dl_Circle_004_mesh_layer_5[];
extern Gfx bob_dl_greenery__mesh_layer_1[];
extern Gfx bob_dl_greenery__mesh_layer_4[];
extern Gfx bob_dl_house_mesh_layer_1[];
extern Gfx bob_dl_Mesh_mesh_layer_1[];
extern Gfx bob_dl_Mesh_mesh_layer_5[];
extern Gfx bob_dl_MovableBox_mesh_layer_1[];
extern Gfx bob_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx bob_dl_final_revert_mesh_layer_1[];
extern Gfx bob_dl_final_revert_mesh_layer_5[];
extern Gfx bob_dl_final_revert_mesh_layer_4[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_002_mesh_layer_1[];
extern Gfx bob_dl_Death_Plane_mesh_layer_1[];
extern Gfx bob_dl_final_revert_mesh_layer_1_001[];
extern Gfx bob_dl_Circle_mesh_layer_1[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_final_revert_mesh_layer_1_002[];
