extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
#include "src/game/camera.h"

extern struct CutsceneSplinePoint bob_area_1_spline_mh_cam[];
extern struct CutsceneSplinePoint bob_area_1_spline_mh_foc[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern u8 bob_dl_castle_grounds_textures_0B400_rgba16_ci8[];
extern u8 bob_dl_castle_grounds_textures_0B400_rgba16_pal_rgba16[];
extern u8 bob_dl_GM4E01_690ee59b_14_mip2_ci4_ci4[];
extern u8 bob_dl_GM4E01_690ee59b_14_mip2_ci4_pal_rgba16[];
extern u8 bob_dl_side_ci8[];
extern u8 bob_dl_side_pal_rgba16[];
extern u8 bob_dl_dirt_ci4[];
extern u8 bob_dl_dirt_pal_rgba16[];
extern u8 bob_dl_wf_textures_03800_rgba16_rgba16[];
extern u8 bob_dl_mush_ci8[];
extern u8 bob_dl_mush_pal_rgba16[];
extern u8 bob_dl_jrb_textures_00000_rgba16_ci8[];
extern u8 bob_dl_jrb_textures_00000_rgba16_pal_rgba16[];
extern Vtx bob_dl_Bridge_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Bridge_mesh_layer_1_vtx_0[438];
extern Gfx bob_dl_Bridge_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Geometry_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Geometry_mesh_layer_1_vtx_0[239];
extern Gfx bob_dl_Geometry_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Geometry_mesh_layer_1_vtx_1[175];
extern Gfx bob_dl_Geometry_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Geometry_mesh_layer_1_vtx_2[146];
extern Gfx bob_dl_Geometry_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Geometry_mesh_layer_1_vtx_3[63];
extern Gfx bob_dl_Geometry_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Mushrooms_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Mushrooms_mesh_layer_1_vtx_0[477];
extern Gfx bob_dl_Mushrooms_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Mushrooms_mesh_layer_1_vtx_1[434];
extern Gfx bob_dl_Mushrooms_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Water_Box_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[214];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_f3dlite_material_005[];
extern Gfx mat_revert_bob_dl_f3dlite_material_005[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_revert_bob_dl_f3dlite_material[];
extern Gfx mat_bob_dl_f3dlite_material_006[];
extern Gfx mat_revert_bob_dl_f3dlite_material_006[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_revert_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_f3dlite_material_002[];
extern Gfx mat_revert_bob_dl_f3dlite_material_002[];
extern Gfx mat_bob_dl_f3dlite_material_003[];
extern Gfx mat_revert_bob_dl_f3dlite_material_003[];
extern Gfx mat_bob_dl_f3dlite_material_004[];
extern Gfx mat_revert_bob_dl_f3dlite_material_004[];
extern Gfx mat_bob_dl_sm64_water_mat[];
extern Gfx mat_revert_bob_dl_sm64_water_mat[];
extern Gfx bob_dl_Bridge_mesh_layer_1[];
extern Gfx bob_dl_Geometry_mesh_layer_1[];
extern Gfx bob_dl_Mushrooms_mesh_layer_1[];
extern Gfx bob_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx bob_dl_final_revert_mesh_layer_1[];
extern Gfx bob_dl_final_revert_mesh_layer_5[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx final_revert_001[];
