extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
#include "src/game/camera.h"

extern struct CutsceneSplinePoint bob_area_1_spline_mh_cam[];
extern struct CutsceneSplinePoint bob_area_1_spline_mh_cam2[];
extern struct CutsceneSplinePoint bob_area_1_spline_mh_cam3[];
extern struct CutsceneSplinePoint bob_area_1_spline_mh_foc[];
extern struct CutsceneSplinePoint bob_area_1_spline_mh_foc2[];
extern struct CutsceneSplinePoint bob_area_1_spline_mh_foc3[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern u8 bob_dl_wf_textures_02000_rgba16_rgba16[];
extern u8 bob_dl_wf_textures_02800_rgba16_rgba16[];
extern u8 bob_dl_rr_textures_01000_rgba16_ci8[];
extern u8 bob_dl_rr_textures_01000_rgba16_pal_rgba16[];
extern u8 bob_dl_brick_ci8[];
extern u8 bob_dl_brick_pal_rgba16[];
extern u8 bob_dl_material_1_ci4[];
extern u8 bob_dl_material_1_x_Acid_pal_rgba16[];
extern u8 bob_dl_Acid_ci8[];
extern u8 bob_dl_material_2_ci4[];
extern u8 bob_dl_material_2_x_Dirt_pal_rgba16[];
extern u8 bob_dl_Dirt_ci4[];
extern u8 bob_dl_dirt_ci4[];
extern u8 bob_dl_dirt_pal_rgba16[];
extern u8 bob_dl_mush_ci8[];
extern u8 bob_dl_mush_pal_rgba16[];
extern u8 bob_dl_water_ci4[];
extern u8 bob_dl_water_pal_rgba16[];
extern u8 bob_dl_NSwitch_GameWatch_Legendary_Sideimg_Bush_rgba16[];
extern u8 bob_dl_mushroom_ci4[];
extern u8 bob_dl_mushroom_pal_rgba16[];
extern Vtx bob_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Circle_mesh_layer_1_vtx_0[16];
extern Gfx bob_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Circle_mesh_layer_1_vtx_1[64];
extern Gfx bob_dl_Circle_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Circle_001_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Circle_001_mesh_layer_1_vtx_0[16];
extern Gfx bob_dl_Circle_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Circle_001_mesh_layer_1_vtx_1[67];
extern Gfx bob_dl_Circle_001_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Circle_002_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Circle_002_mesh_layer_1_vtx_0[16];
extern Gfx bob_dl_Circle_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Circle_002_mesh_layer_1_vtx_1[64];
extern Gfx bob_dl_Circle_002_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Circle_003_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Circle_003_mesh_layer_1_vtx_0[16];
extern Gfx bob_dl_Circle_003_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Circle_003_mesh_layer_1_vtx_1[64];
extern Gfx bob_dl_Circle_003_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Circle_004_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Circle_004_mesh_layer_1_vtx_0[16];
extern Gfx bob_dl_Circle_004_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Circle_004_mesh_layer_1_vtx_1[64];
extern Gfx bob_dl_Circle_004_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_mesh_layer_1_vtx_0[929];
extern Gfx bob_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx bob_dl_DeathPlane_001_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_DeathPlane_001_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_DeathPlane_001_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Mesh_mesh_layer_1_vtx_0[235];
extern Gfx bob_dl_Mesh_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Mesh_mesh_layer_1_vtx_1[599];
extern Gfx bob_dl_Mesh_mesh_layer_1_tri_1[];
extern Vtx bob_dl_MovableBox_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_MovableBox_mesh_layer_1_vtx_0[44];
extern Gfx bob_dl_MovableBox_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Mushroom_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Mushroom_mesh_layer_1_vtx_0[880];
extern Gfx bob_dl_Mushroom_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Mushroom_mesh_layer_1_vtx_1[555];
extern Gfx bob_dl_Mushroom_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Mushroom_009_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Mushroom_009_mesh_layer_1_vtx_0[80];
extern Gfx bob_dl_Mushroom_009_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Mushroom_009_mesh_layer_1_vtx_1[60];
extern Gfx bob_dl_Mushroom_009_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Water_Box_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[352];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[168];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_4_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_4_vtx_0[28];
extern Gfx bob_dl_Cube_mesh_layer_4_tri_0[];
extern Vtx bob_dl_DeathPlane_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_DeathPlane_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_DeathPlane_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_f3dlite_material_006[];
extern Gfx mat_revert_bob_dl_f3dlite_material_006[];
extern Gfx mat_bob_dl_f3dlite_material_007[];
extern Gfx mat_revert_bob_dl_f3dlite_material_007[];
extern Gfx mat_bob_dl_f3dlite_material_003[];
extern Gfx mat_revert_bob_dl_f3dlite_material_003[];
extern Gfx mat_bob_dl_f3dlite_material_011[];
extern Gfx mat_revert_bob_dl_f3dlite_material_011[];
extern Gfx mat_bob_dl_material_1_001_f3d[];
extern Gfx mat_revert_bob_dl_material_1_001_f3d[];
extern Gfx mat_bob_dl_material_2_001_f3d[];
extern Gfx mat_revert_bob_dl_material_2_001_f3d[];
extern Gfx mat_bob_dl_f3dlite_material_004[];
extern Gfx mat_revert_bob_dl_f3dlite_material_004[];
extern Gfx mat_bob_dl_f3dlite_material_005[];
extern Gfx mat_revert_bob_dl_f3dlite_material_005[];
extern Gfx mat_bob_dl_sm64_water_mat[];
extern Gfx mat_revert_bob_dl_sm64_water_mat[];
extern Gfx mat_bob_dl_f3dlite_material_008[];
extern Gfx mat_revert_bob_dl_f3dlite_material_008[];
extern Gfx mat_bob_dl_f3dlite_material_009[];
extern Gfx mat_revert_bob_dl_f3dlite_material_009[];
extern Gfx mat_bob_dl_f3dlite_material_010[];
extern Gfx mat_revert_bob_dl_f3dlite_material_010[];
extern Gfx bob_dl_Circle_mesh_layer_1[];
extern Gfx bob_dl_Circle_001_mesh_layer_1[];
extern Gfx bob_dl_Circle_002_mesh_layer_1[];
extern Gfx bob_dl_Circle_003_mesh_layer_1[];
extern Gfx bob_dl_Circle_004_mesh_layer_1[];
extern Gfx bob_dl_Cylinder_mesh_layer_1[];
extern Gfx bob_dl_DeathPlane_001_mesh_layer_5[];
extern Gfx bob_dl_Mesh_mesh_layer_1[];
extern Gfx bob_dl_MovableBox_mesh_layer_1[];
extern Gfx bob_dl_Mushroom_mesh_layer_1[];
extern Gfx bob_dl_Mushroom_009_mesh_layer_1[];
extern Gfx bob_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx bob_dl_final_revert_mesh_layer_1[];
extern Gfx bob_dl_final_revert_mesh_layer_5[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_4[];
extern Gfx bob_dl_DeathPlane_mesh_layer_5[];
extern Gfx final_revert_001[];
extern Gfx bob_dl_final_revert_mesh_layer_4[];
extern Gfx final_revert_002[];
