extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
#include "src/game/camera.h"

extern struct CutsceneSplinePoint wf_area_1_spline_c_001[];
extern struct CutsceneSplinePoint wf_area_1_spline_c_002[];
extern struct CutsceneSplinePoint wf_area_1_spline_c_003[];
extern struct CutsceneSplinePoint wf_area_1_spline_neFoc[];
extern struct CutsceneSplinePoint wf_area_1_spline_nePos[];
extern struct CutsceneSplinePoint wf_area_1_spline_s_001[];
extern struct CutsceneSplinePoint wf_area_1_spline_s_002[];
extern struct CutsceneSplinePoint wf_area_1_spline_s_003[];
extern u8 wf_dl_DK_grass_ci4_1__1__ci4[];
extern u8 wf_dl_DK_grass_ci4_1__1__pal_rgba16[];
extern u8 wf_dl_stone_granite_rgba16_ci8[];
extern u8 wf_dl_stone_granite_rgba16_pal_rgba16[];
extern u8 wf_dl_YukkinaTreeBreak00_ci4_ci4[];
extern u8 wf_dl_YukkinaTreeBreak00_ci4_pal_rgba16[];
extern u8 wf_dl_BigTreeWoodC_rgba16_ci8[];
extern u8 wf_dl_BigTreeWoodC_rgba16_pal_rgba16[];
extern u8 wf_dl__1chain_ci4_ci4[];
extern u8 wf_dl__1chain_ci4_pal_rgba16[];
extern u8 wf_dl__11111texKinokoRed_ci4_ci4[];
extern u8 wf_dl__11111texKinokoRed_ci4_pal_rgba16[];
extern u8 wf_dl__12donebpyro2ycdi_rgba16_rgba16[];
extern u8 wf_dl_ng_nukirgba16_rgba16_rgba16[];
extern u8 wf_dl_Jacey_snowman_carrot_texture_i8_i8[];
extern u8 wf_dl__2EB6628BD0351A22F3163295E64E9B63_ci4_ci4[];
extern u8 wf_dl__2EB6628BD0351A22F3163295E64E9B63_ci4_pal_rgba16[];
extern u8 wf_dl_door_birch_lower_ci4_ci4[];
extern u8 wf_dl_door_birch_lower_ci4_pal_rgba16[];
extern u8 wf_dl__7_ci8_ci8[];
extern u8 wf_dl__7_ci8_pal_rgba16[];
extern u8 wf_dl_leaf_half_rgba16_ci8[];
extern u8 wf_dl_leaf_half_rgba16_pal_rgba16[];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_1_vtx_0[168];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_1_tri_0[];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_1_vtx_1[86];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_1_tri_1[];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_1_vtx_2[435];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_1_tri_2[];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_1_vtx_3[110];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_1_tri_3[];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_1_vtx_4[102];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_1_tri_4[];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_1_vtx_5[96];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_1_tri_5[];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_1_vtx_6[46];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_1_tri_6[];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_1_vtx_7[40];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_1_tri_7[];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_1_vtx_8[104];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_1_tri_8[];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_1_vtx_9[36];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_1_tri_9[];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_4_vtx_cull[8];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_4_vtx_0[54];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_4_tri_0[];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_4_vtx_1[67];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_4_tri_1[];
extern Vtx wf_dl_bob_area_1_collision_mesh_layer_4_vtx_2[12];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_4_tri_2[];
extern Gfx mat_wf_dl_f3dlite_material_013[];
extern Gfx mat_revert_wf_dl_f3dlite_material_013[];
extern Gfx mat_wf_dl_f3dlite_material_014[];
extern Gfx mat_revert_wf_dl_f3dlite_material_014[];
extern Gfx mat_wf_dl_f3dlite_material_015[];
extern Gfx mat_revert_wf_dl_f3dlite_material_015[];
extern Gfx mat_wf_dl_f3dlite_material_016[];
extern Gfx mat_revert_wf_dl_f3dlite_material_016[];
extern Gfx mat_wf_dl_f3dlite_material_017[];
extern Gfx mat_revert_wf_dl_f3dlite_material_017[];
extern Gfx mat_wf_dl_f3dlite_material_018[];
extern Gfx mat_revert_wf_dl_f3dlite_material_018[];
extern Gfx mat_wf_dl_f3dlite_material_019[];
extern Gfx mat_revert_wf_dl_f3dlite_material_019[];
extern Gfx mat_wf_dl_f3dlite_material_020[];
extern Gfx mat_revert_wf_dl_f3dlite_material_020[];
extern Gfx mat_wf_dl_f3dlite_material_021[];
extern Gfx mat_revert_wf_dl_f3dlite_material_021[];
extern Gfx mat_wf_dl_f3dlite_material_022[];
extern Gfx mat_revert_wf_dl_f3dlite_material_022[];
extern Gfx mat_wf_dl_f3dlite_material_023[];
extern Gfx mat_revert_wf_dl_f3dlite_material_023[];
extern Gfx mat_wf_dl_f3dlite_material[];
extern Gfx mat_revert_wf_dl_f3dlite_material[];
extern Gfx mat_wf_dl_f3dlite_material_002[];
extern Gfx mat_revert_wf_dl_f3dlite_material_002[];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_1[];
extern Gfx wf_dl_bob_area_1_collision_mesh_layer_4[];
extern Gfx wf_dl_final_revert_mesh_layer_1[];
extern Gfx wf_dl_final_revert_mesh_layer_4[];
