extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
#include "src/game/camera.h"

extern struct CutsceneSplinePoint wf_area_1_spline_cam1[];
extern struct CutsceneSplinePoint wf_area_1_spline_foc1[];
extern const Vec4s wf_area_1_spline_RockPath[];
extern u8 wf_dl_Dirt_2_ci4[];
extern u8 wf_dl_Dirt_2_pal_rgba16[];
extern u8 wf_dl_water_ci8[];
extern u8 wf_dl_water_pal_rgba16[];
extern u8 wf_dl_Window_i8[];
extern Vtx wf_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Circle_mesh_layer_1_vtx_0[954];
extern Gfx wf_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_mesh_layer_5_vtx_cull[8];
extern Vtx wf_dl_Plane_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Plane_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Plane_001_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_001_mesh_layer_1_vtx_1[72];
extern Gfx wf_dl_Plane_001_mesh_layer_1_tri_1[];
extern Gfx mat_wf_dl_f3dlite_material_002[];
extern Gfx mat_revert_wf_dl_f3dlite_material_002[];
extern Gfx mat_wf_dl_sm64_water_mat[];
extern Gfx mat_revert_wf_dl_sm64_water_mat[];
extern Gfx mat_wf_dl_f3dlite_material[];
extern Gfx mat_revert_wf_dl_f3dlite_material[];
extern Gfx mat_wf_dl_f3dlite_material_001[];
extern Gfx mat_revert_wf_dl_f3dlite_material_001[];
extern Gfx wf_dl_Circle_mesh_layer_1[];
extern Gfx wf_dl_Plane_mesh_layer_5[];
extern Gfx wf_dl_Plane_001_mesh_layer_1[];
extern Gfx wf_dl_final_revert_mesh_layer_1[];
extern Gfx wf_dl_final_revert_mesh_layer_5[];
