extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
#include "src/game/camera.h"

extern struct CutsceneSplinePoint wf_area_1_spline_cam[];
extern struct CutsceneSplinePoint wf_area_1_spline_cam_001[];
extern struct CutsceneSplinePoint wf_area_1_spline_cam_002[];
extern struct CutsceneSplinePoint wf_area_1_spline_foc[];
extern struct CutsceneSplinePoint wf_area_1_spline_foc_001[];
extern struct CutsceneSplinePoint wf_area_1_spline_foc_002[];
extern u8 wf_dl_NEWON0E223_i4_i4[];
extern u8 wf_dl_mulittex1_i4_i4[];
extern u8 wf_dl_GZLE01_ce05cd90_14_ci4_ci4[];
extern u8 wf_dl_GZLE01_ce05cd90_14_ci4_pal_rgba16[];
extern u8 wf_dl__19E763D603106FE29AD4BD3A423C1B00_ci8_ci8[];
extern u8 wf_dl__19E763D603106FE29AD4BD3A423C1B00_ci8_pal_rgba16[];
extern u8 wf_dl_ki_mizu_ci8_i8[];
extern u8 wf_dl_WaterTestgrey_i4_i4[];
extern Vtx wf_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Cylinder_mesh_layer_1_vtx_0[40];
extern Gfx wf_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cylinder_mesh_layer_1_vtx_1[688];
extern Gfx wf_dl_Cylinder_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Cylinder_mesh_layer_1_vtx_2[396];
extern Gfx wf_dl_Cylinder_mesh_layer_1_tri_2[];
extern Vtx wf_dl_Water_Box_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Water_Box_Mesh_mesh_layer_1_vtx_0[8];
extern Gfx wf_dl_Water_Box_Mesh_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_f3dlite_material_013[];
extern Gfx mat_revert_wf_dl_f3dlite_material_013[];
extern Gfx mat_wf_dl_f3dlite_material_001[];
extern Gfx mat_revert_wf_dl_f3dlite_material_001[];
extern Gfx mat_wf_dl_f3dlite_material_004[];
extern Gfx mat_revert_wf_dl_f3dlite_material_004[];
extern Gfx mat_wf_dl_sm64_water_mat[];
extern Gfx mat_revert_wf_dl_sm64_water_mat[];
extern Gfx wf_dl_Cylinder_mesh_layer_1[];
extern Gfx wf_dl_Water_Box_Mesh_mesh_layer_1[];
extern Gfx wf_dl_final_revert_mesh_layer_1[];
