extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern u8 jrb_dl_lll_textures_01000_rgba16_i8[];
extern u8 jrb_dl_lll_textures_09000_rgba16_ci8[];
extern u8 jrb_dl_lll_textures_09000_rgba16_pal_rgba16[];
extern u8 jrb_dl_lll_textures_05800_rgba16_ci8[];
extern u8 jrb_dl_lll_textures_05800_rgba16_pal_rgba16[];
extern Vtx jrb_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Cylinder_mesh_layer_1_vtx_0[1968];
extern Gfx jrb_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cylinder_002_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Cylinder_002_mesh_layer_1_vtx_0[55];
extern Gfx jrb_dl_Cylinder_002_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_0[16];
extern Gfx jrb_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Plane_001_mesh_layer_1_vtx_0[10];
extern Gfx jrb_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Sphere_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Sphere_mesh_layer_1_vtx_0[30];
extern Gfx jrb_dl_Sphere_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Sphere_001_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Sphere_001_mesh_layer_1_vtx_0[30];
extern Gfx jrb_dl_Sphere_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Sphere_002_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Sphere_002_mesh_layer_1_vtx_0[30];
extern Gfx jrb_dl_Sphere_002_mesh_layer_1_tri_0[];
extern Gfx mat_jrb_dl_f3dlite_material_001[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_001[];
extern Gfx mat_jrb_dl_f3dlite_material[];
extern Gfx mat_revert_jrb_dl_f3dlite_material[];
extern Gfx mat_jrb_dl_f3dlite_material_002[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_002[];
extern Gfx jrb_dl_Cylinder_mesh_layer_1[];
extern Gfx jrb_dl_Cylinder_002_mesh_layer_1[];
extern Gfx jrb_dl_Plane_mesh_layer_1[];
extern Gfx jrb_dl_Plane_001_mesh_layer_1[];
extern Gfx jrb_dl_Sphere_mesh_layer_1[];
extern Gfx jrb_dl_Sphere_001_mesh_layer_1[];
extern Gfx jrb_dl_Sphere_002_mesh_layer_1[];
extern Gfx jrb_dl_final_revert_mesh_layer_1[];
