extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern u8 jrb_dl_DK_grass_ci4_ci4[];
extern u8 jrb_dl_DK_grass_ci4_pal_rgba16[];
extern u8 jrb_dl__7_ci8_ci8[];
extern u8 jrb_dl__7_ci8_pal_rgba16[];
extern Vtx jrb_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Circle_mesh_layer_1_vtx_0[120];
extern Gfx jrb_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Circle_mesh_layer_1_vtx_1[32];
extern Gfx jrb_dl_Circle_mesh_layer_1_tri_1[];
extern Gfx mat_jrb_dl_f3dlite_material[];
extern Gfx mat_revert_jrb_dl_f3dlite_material[];
extern Gfx mat_jrb_dl_f3dlite_material_001[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_001[];
extern Gfx jrb_dl_Circle_mesh_layer_1[];
extern Gfx jrb_dl_final_revert_mesh_layer_1[];
