extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern u8 jrb_dl_jrb_textures_02800_rgba16_ci8[];
extern u8 jrb_dl_jrb_textures_02800_rgba16_pal_rgba16[];
extern u8 jrb_dl_jrb_textures_03800_rgba16_ci8[];
extern u8 jrb_dl_jrb_textures_03800_rgba16_pal_rgba16[];
extern u8 jrb_dl_jrb_textures_07800_rgba16_ci8[];
extern u8 jrb_dl_jrb_textures_07800_rgba16_pal_rgba16[];
extern u8 jrb_dl_jrb_textures_01800_rgba16_ci8[];
extern u8 jrb_dl_jrb_textures_01800_rgba16_pal_rgba16[];
extern u8 jrb_dl_jrb_textures_00000_rgba16_ci8[];
extern u8 jrb_dl_jrb_textures_00000_rgba16_pal_rgba16[];
extern Vtx jrb_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Circle_mesh_layer_1_vtx_0[50];
extern Gfx jrb_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Cylinder_mesh_layer_1_vtx_0[405];
extern Gfx jrb_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cylinder_001_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Cylinder_001_mesh_layer_1_vtx_0[67];
extern Gfx jrb_dl_Cylinder_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Icosphere_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Icosphere_mesh_layer_1_vtx_0[240];
extern Gfx jrb_dl_Icosphere_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Water_Box_Mesh_mesh_layer_5_vtx_cull[8];
extern Vtx jrb_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx jrb_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Gfx mat_jrb_dl_f3dlite_material[];
extern Gfx mat_revert_jrb_dl_f3dlite_material[];
extern Gfx mat_jrb_dl_f3dlite_material_002[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_002[];
extern Gfx mat_jrb_dl_f3dlite_material_003[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_003[];
extern Gfx mat_jrb_dl_f3dlite_material_001[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_001[];
extern Gfx mat_jrb_dl_sm64_water_mat[];
extern Gfx mat_revert_jrb_dl_sm64_water_mat[];
extern Gfx jrb_dl_Circle_mesh_layer_1[];
extern Gfx jrb_dl_Cylinder_mesh_layer_1[];
extern Gfx jrb_dl_Cylinder_001_mesh_layer_1[];
extern Gfx jrb_dl_Icosphere_mesh_layer_1[];
extern Gfx jrb_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx jrb_dl_final_revert_mesh_layer_1[];
extern Gfx jrb_dl_final_revert_mesh_layer_5[];
