extern const GeoLayout bouncingShroom_geo[];
extern u8 bouncingShroom__11111texKinokoRed_ci4_ci4[];
extern u8 bouncingShroom__11111texKinokoRed_ci4_pal_rgba16[];
extern Vtx bouncingShroom_Geometry1_mesh_layer_1_vtx_cull[8];
extern Vtx bouncingShroom_Geometry1_mesh_layer_1_vtx_0[68];
extern Gfx bouncingShroom_Geometry1_mesh_layer_1_tri_0[];
extern Gfx mat_bouncingShroom_f3dlite_material_001[];
extern Gfx mat_revert_bouncingShroom_f3dlite_material_001[];
extern Gfx bouncingShroom_Geometry1_mesh_layer_1[];
extern Gfx bouncingShroom_final_revert_mesh_layer_1[];
