extern const GeoLayout pss_area_1_geo[];
extern const GeoLayout pss_area_1[];
extern const Collision pss_area_1_collision[];
extern const MacroObject pss_area_1_macro_objs[];
extern Lights1 pss_dl_f3dlite_material_lights;
extern Lights1 pss_dl_f3dlite_material_002_lights;
extern u8 pss_dl_BigTreeCourse_ci4_ci4[];
extern u8 pss_dl_BigTreeCourse_ci4_pal_rgba16[];
extern u8 pss_dl_YukkinaTreeBreak00_ci4_ci4[];
extern u8 pss_dl_YukkinaTreeBreak00_ci4_pal_rgba16[];
extern u8 pss_dl_white_eye_ia8[];
extern u8 pss_dl_siun_ia8[];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_0[79];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_1[218];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx pss_dl_Cube_mesh_layer_1_vtx_2[61];
extern Gfx pss_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx pss_dl_Cube_mesh_layer_5_vtx_cull[8];
extern Vtx pss_dl_Cube_mesh_layer_5_vtx_0[4];
extern Gfx pss_dl_Cube_mesh_layer_5_tri_0[];
extern Gfx mat_pss_dl_f3dlite_material[];
extern Gfx mat_revert_pss_dl_f3dlite_material[];
extern Gfx mat_pss_dl_f3dlite_material_002[];
extern Gfx mat_revert_pss_dl_f3dlite_material_002[];
extern Gfx mat_pss_dl_f3dlite_material_003[];
extern Gfx mat_revert_pss_dl_f3dlite_material_003[];
extern Gfx mat_pss_dl_f3dlite_material_004[];
extern Gfx mat_revert_pss_dl_f3dlite_material_004[];
extern Gfx pss_dl_Cube_mesh_layer_1[];
extern Gfx pss_dl_Cube_mesh_layer_5[];
extern Gfx pss_dl_final_revert_mesh_layer_1[];
extern Gfx pss_dl_final_revert_mesh_layer_5[];
