extern const GeoLayout thi_area_1_geo[];
extern const GeoLayout thi_area_1[];
extern const Collision thi_area_1_collision[];
extern const MacroObject thi_area_1_macro_objs[];
extern u8 thi_dl_inside_castle_textures_04000_rgba16_rgba16[];
extern u8 thi_dl_GM4E01_690ee59b_14_mip2_ci4_ci4[];
extern u8 thi_dl_GM4E01_690ee59b_14_mip2_ci4_pal_rgba16[];
extern Vtx thi_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx thi_dl_Level_Mesh_mesh_layer_1_vtx_0[71];
extern Gfx thi_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Level_Mesh_mesh_layer_1_vtx_1[78];
extern Gfx thi_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Vtx thi_dl_Level_Mesh_mesh_layer_1_vtx_2[218];
extern Gfx thi_dl_Level_Mesh_mesh_layer_1_tri_2[];
extern Gfx mat_thi_dl_Grass_Example[];
extern Gfx mat_revert_thi_dl_Grass_Example[];
extern Gfx mat_thi_dl_f3dlite_material_001[];
extern Gfx mat_revert_thi_dl_f3dlite_material_001[];
extern Gfx mat_thi_dl_f3dlite_material_002[];
extern Gfx mat_revert_thi_dl_f3dlite_material_002[];
extern Gfx thi_dl_Level_Mesh_mesh_layer_1[];
extern Gfx thi_dl_final_revert_mesh_layer_1[];
