extern const GeoLayout thi_area_1_geo[];
extern const GeoLayout thi_area_1[];
extern const Collision thi_area_1_collision[];
extern const MacroObject thi_area_1_macro_objs[];
extern u8 thi_dl_DK_grass_ci4_1__1__ci4[];
extern u8 thi_dl_DK_grass_ci4_1__1__pal_rgba16[];
extern u8 thi_dl_cloud1_ci4_ci4[];
extern u8 thi_dl_cloud1_ci4_pal_rgba16[];
extern u8 thi_dl_sun_ia8[];
extern u8 thi_dl_cloud_ia8[];
extern Vtx thi_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx thi_dl_Plane_mesh_layer_1_vtx_0[13];
extern Gfx thi_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Plane_mesh_layer_1_vtx_1[27];
extern Gfx thi_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx thi_dl_Plane_mesh_layer_5_vtx_cull[8];
extern Vtx thi_dl_Plane_mesh_layer_5_vtx_0[4];
extern Gfx thi_dl_Plane_mesh_layer_5_tri_0[];
extern Vtx thi_dl_Plane_mesh_layer_5_vtx_1[12];
extern Gfx thi_dl_Plane_mesh_layer_5_tri_1[];
extern Gfx mat_thi_dl_f3dlite_material[];
extern Gfx mat_revert_thi_dl_f3dlite_material[];
extern Gfx mat_thi_dl_f3dlite_material_003[];
extern Gfx mat_revert_thi_dl_f3dlite_material_003[];
extern Gfx mat_thi_dl_f3dlite_material_009[];
extern Gfx mat_revert_thi_dl_f3dlite_material_009[];
extern Gfx mat_thi_dl_f3dlite_material_010[];
extern Gfx mat_revert_thi_dl_f3dlite_material_010[];
extern Gfx thi_dl_Plane_mesh_layer_1[];
extern Gfx thi_dl_Plane_mesh_layer_5[];
extern Gfx thi_dl_final_revert_mesh_layer_1[];
extern Gfx thi_dl_final_revert_mesh_layer_5[];
