extern const GeoLayout thi_area_1_geo[];
extern const GeoLayout thi_area_1[];
extern const Collision thi_area_1_collision[];
extern const MacroObject thi_area_1_macro_objs[];
extern u8 thi_dl_inside_castle_textures_04000_rgba16_rgba16[];
extern Vtx thi_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx thi_dl_Cube_mesh_layer_1_vtx_0[201];
extern Gfx thi_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx thi_dl_Cube_mesh_layer_1_vtx_1[48];
extern Gfx thi_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx thi_dl_Cube_mesh_layer_1_vtx_2[12];
extern Gfx thi_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx thi_dl_Cube_mesh_layer_1_vtx_3[12];
extern Gfx thi_dl_Cube_mesh_layer_1_tri_3[];
extern Vtx thi_dl_Cube_mesh_layer_1_vtx_4[12];
extern Gfx thi_dl_Cube_mesh_layer_1_tri_4[];
extern Vtx thi_dl_Cube_mesh_layer_1_vtx_5[12];
extern Gfx thi_dl_Cube_mesh_layer_1_tri_5[];
extern Vtx thi_dl_Cube_mesh_layer_1_vtx_6[12];
extern Gfx thi_dl_Cube_mesh_layer_1_tri_6[];
extern Gfx mat_thi_dl_f3dlite_material_001[];
extern Gfx mat_revert_thi_dl_f3dlite_material_001[];
extern Gfx mat_thi_dl_f3dlite_material_002[];
extern Gfx mat_revert_thi_dl_f3dlite_material_002[];
extern Gfx mat_thi_dl_f3dlite_material_004[];
extern Gfx mat_revert_thi_dl_f3dlite_material_004[];
extern Gfx mat_thi_dl_f3dlite_material_005[];
extern Gfx mat_revert_thi_dl_f3dlite_material_005[];
extern Gfx mat_thi_dl_f3dlite_material_006[];
extern Gfx mat_revert_thi_dl_f3dlite_material_006[];
extern Gfx mat_thi_dl_f3dlite_material_007[];
extern Gfx mat_revert_thi_dl_f3dlite_material_007[];
extern Gfx mat_thi_dl_f3dlite_material_008[];
extern Gfx mat_revert_thi_dl_f3dlite_material_008[];
extern Gfx thi_dl_Cube_mesh_layer_1[];
extern Gfx thi_dl_final_revert_mesh_layer_1[];
